### ISSUE TITLE
netmri-bootstrap.py check errors out

### ISSUE THREAD

**Issue by seefor** [infobloxopen/netmri-bootstrap#3]
Wanted to report the following:
`sbaksh@django:~$ netmri-bootstrap.py check
Traceback (most recent call last):
  File "/home/sbaksh/.local/bin/netmri-bootstrap.py", line 123, in <module>
    bs.check_netmri(local_only=args.brief)
  File "/home/sbaksh/.local/lib/python3.8/site-packages/netmri_bootstrap/__init__.py", line 125, in check_netmri
    for git_item in self.repo.object_index[klass.__name__].values():
KeyError: 'ConfigList'`

I do not have the time to look deeper into the code for the error but I figured I'll post it here for someone else to take a look.  But I will come back to it

Thanks

**Comment by L-Eugene** [comment]
Fixed in pull request #4
